import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class PresentationCompanionTests(unittest.TestCase):
    def test_schema_and_api_support_synced_presentation_state(self):
        db_source = (ROOT / "app" / "db.py").read_text()
        main_source = (ROOT / "app" / "main.py").read_text()

        self.assertIn("presentation_state", db_source)
        self.assertIn("participant_responses", db_source)
        self.assertIn("participant_response_votes", db_source)
        self.assertIn("presentation_artifacts", db_source)
        self.assertIn("presentation_slide_overrides", db_source)
        self.assertIn("presentation_slides", db_source)
        self.assertIn("slide_id TEXT", db_source)
        self.assertIn("slide_title TEXT", db_source)
        self.assertIn("/api/presentation/state", main_source)
        self.assertIn("/api/sessions/{sid}/responses", main_source)
        self.assertIn("/api/sessions/{sid}/responses/{response_id}/vote", main_source)
        self.assertIn("INSERT INTO participant_questions (id, session_id, text, slide_id, slide_title)", main_source)
        self.assertIn("/api/podium/artifacts", main_source)
        self.assertIn("/api/podium/slide-overrides", main_source)
        self.assertIn("/api/podium/slides/{slide_id}", main_source)
        self.assertIn("UPDATE presentation_slides SET is_deleted=true", main_source)
        self.assertIn("/api/podium/slides", main_source)
        self.assertIn("/api/podium/slides/order", main_source)
        self.assertIn("active_slide_payload", main_source)
        self.assertIn("TRUNCATE runs, instructions, sessions, participant_questions, participant_response_votes, participant_responses, presentation_artifacts", main_source)

    def test_presentation_definitions_include_passive_and_interactive_slices(self):
        source = (ROOT / "static" / "presentation.js").read_text()

        self.assertIn("PRESENTATION_SLIDES", source)
        self.assertIn('template: "standard"', source)
        self.assertIn('template: "interaction"', source)
        self.assertIn('template: "qna-review"', source)
        self.assertIn('template: "suggestion-capture"', source)
        self.assertIn('template: "requirements-capture"', source)
        self.assertIn('template: "workflow-capture"', source)
        self.assertIn('template: "bot-results"', source)
        self.assertIn('"welcome"', source)
        self.assertIn('"baseline-build"', source)
        self.assertIn('"requirements-gathering"', source)
        self.assertIn('"requirements-build"', source)
        self.assertIn('"process-map"', source)
        self.assertIn('"qna-review"', source)
        self.assertIn('participantMode: "passive"', source)
        self.assertIn('participantMode: "bot"', source)
        self.assertIn('participantMode: "requirements"', source)
        self.assertIn('participantMode: "suggestion"', source)
        self.assertIn('participantMode: "process"', source)

    def test_participant_app_renders_companion_modes(self):
        source = (ROOT / "static" / "app.js").read_text()

        self.assertIn("loadPresentationState", source)
        self.assertIn("renderCompanion", source)
        self.assertIn("renderQna", source)
        self.assertIn("renderRequirements", source)
        self.assertIn("renderSuggestion", source)
        self.assertIn("renderProcess", source)
        self.assertIn("captured_requirements", source)
        self.assertIn("submitResponse", source)
        self.assertIn("voteResponse", source)
        self.assertIn("activeSlide", source)
        self.assertIn("activeSlideBanner", source)
        self.assertIn("active-slide-banner", source)

    def test_podium_app_renders_presentation_controls_and_artifacts(self):
        source = (ROOT / "static" / "podium.js").read_text()
        style = (ROOT / "static" / "style.css").read_text()

        self.assertIn("presentationState", source)
        self.assertIn("renderPresentation", source)
        self.assertIn("activateSlide", source)
        self.assertIn("saveArtifact", source)
        self.assertIn("renderByTemplate", source)
        self.assertIn("renderInteractionSlide", source)
        self.assertIn("Assistant Builder slide", source)
        self.assertIn("Open the Assistant Builder on your phone.", source)
        self.assertIn("interactionPromptText", source)
        self.assertIn("${bullets ? `<ul>${bullets}</ul>` : \"\"}", source)
        self.assertIn("${esc(interactionPromptText(slide))}", source)
        self.assertIn("renderQnaReviewSlide", source)
        self.assertIn("questionSlideLabel", source)
        self.assertIn("question-slide-pill", source)
        self.assertIn("renderRequirementsSlide", source)
        self.assertIn("renderSuggestionSlide", source)
        self.assertIn("captured_suggestions", source)
        self.assertIn("renderProcessSlide", source)
        self.assertIn("renderLiveSlide", source)
        self.assertIn("archiveQuestion", source)
        self.assertIn("captured-requirements", source)
        self.assertIn("requirements-idea-card", source)
        self.assertIn("requirements-idea-pool", source)
        self.assertIn("capturedRequirementResponseIds", source)
        self.assertIn("availableResponses", source)
        self.assertIn("response_id: item.id", source)
        self.assertIn(".requirements-idea-card", style)
        self.assertIn(".question-slide-pill", style)
        self.assertIn("-webkit-line-clamp:2", style)
        self.assertIn("process-stage-board", source)
        self.assertIn("processItemResponseIds", source)
        self.assertIn("availableProcessResponses", source)
        self.assertIn("item.response_id !== responseId", source)
        self.assertIn("slideOverrides", source)
        self.assertIn("effectiveSlide", source)
        self.assertIn("openSlideEditor", source)
        self.assertIn("saveSlideOverride", source)
        self.assertIn("resetSlideOverride", source)
        self.assertIn("deleteSlide", source)
        self.assertIn("SLIDE_TEMPLATE_OPTIONS", source)
        self.assertIn("templateDefaults", source)
        self.assertIn("edit-template", source)
        self.assertIn("edit-participant-mode", source)
        self.assertIn('template: document.querySelector("#edit-template").value', source)
        self.assertIn('participantMode: document.querySelector("#edit-participant-mode").value', source)
        self.assertIn("Delete slide", source)
        self.assertIn("Are you sure?", source)
        self.assertIn("confirm-delete-slide", source)
        self.assertIn("/api/podium/slide-overrides/", source)
        self.assertIn("edit-slide-panel", source)
        self.assertIn("deckSlides", source)
        self.assertIn("renderSlideList", source)
        self.assertIn("createBlankSlide", source)
        self.assertIn("saveSlideOrder", source)
        self.assertIn("slide-list-panel", source)
        self.assertIn("SLIDE_ASSIGNEES", source)
        self.assertIn('["JS", "MC", "MH", "EW"]', source)
        self.assertIn("SLIDE_DURATIONS", source)
        self.assertIn("[2, 5, 10, 15]", source)
        self.assertIn("slidePlanningControls", source)
        self.assertIn("slide-assignee-select", source)
        self.assertIn("slide-duration-select", source)
        self.assertIn("saveSlidePlanning", source)
        self.assertIn("live-slide-pill", source)
        self.assertIn("clearSlideDragState", source)
        self.assertIn("slideRowPositions", source)
        self.assertIn("animateSlideListFrom", source)
        self.assertIn("slide-drop-zone", source)
        self.assertIn("data-drop-index", source)
        self.assertIn("reorderSlideToIndex", source)
        self.assertIn("drop-target", source)
        self.assertIn("dragging", source)
        self.assertIn('draggable="true" data-slide-id=', source)
        self.assertIn('draggable="false"', source)
        self.assertIn("ArrowRight", source)
        self.assertIn("ArrowLeft", source)
        self.assertIn("reveal-controls", source)
        self.assertIn("presenter-hint", source)
        self.assertIn('title: "Stage 1"', source)
        self.assertIn('title: "Stage 2"', source)
        self.assertNotIn('title: "First contact"', source)
        self.assertNotIn('title: "Understand the enquiry"', source)
        self.assertNotIn('class="badge edited-badge">Edited</span>', source)
        self.assertNotIn('<p class="eyebrow">${esc(slide.section)}</p>', source)

    def test_standard_slides_accept_and_render_uploaded_images(self):
        source = (ROOT / "static" / "podium.js").read_text()
        style = (ROOT / "static" / "style.css").read_text()

        self.assertIn('id="edit-slide-image" type="file"', source)
        self.assertIn('accept="image/jpeg,image/png,image/webp"', source)
        self.assertIn("MAX_SLIDE_IMAGE_BYTES", source)
        self.assertIn("URL.createObjectURL(file)", source)
        self.assertIn("uploadSlideImage", source)
        self.assertIn('/image`, { method: "DELETE"', source)
        self.assertIn("image: savedImage", source)
        self.assertIn('class="slide-image-frame"', source)
        self.assertIn('bullets ? "has-bullets" : "no-bullets"', source)
        self.assertIn(".standard-slide.has-image.has-bullets", style)
        self.assertIn("grid-template-columns:minmax(0,1.08fr) minmax(320px,.92fr)", style)
        self.assertIn(".standard-slide.no-bullets .slide-image-frame", style)

    def test_slide_editor_is_template_aware_and_previews_both_surfaces(self):
        source = (ROOT / "static" / "podium.js").read_text()
        style = (ROOT / "static" / "style.css").read_text()

        self.assertIn("TEMPLATE_EDITOR_FIELDS", source)
        self.assertIn('data-editor-field="body"', source)
        self.assertIn('data-editor-field="bullets"', source)
        self.assertIn('data-editor-field="phonePrompt"', source)
        self.assertIn("function syncEditorFields()", source)
        self.assertIn("function updateSlideEditorPreview()", source)
        self.assertIn("function previewTemplateHint(template)", source)
        self.assertIn("editor-slide-preview", source)
        self.assertIn("editor-phone-preview", source)
        self.assertIn("preview-slide-image", source)
        self.assertIn("editor-fit-warning", source)
        self.assertIn("Discard unsaved slide changes?", source)
        self.assertIn(".edit-slide-actions{position:sticky", style)
        self.assertIn(".slide-editor-preview", style)

    def test_slide_planning_values_are_normalised_and_labelled(self):
        source = (ROOT / "static" / "podium.js").read_text()
        style = (ROOT / "static" / "style.css").read_text()

        self.assertIn("function normaliseSlidePlanning(slide)", source)
        self.assertIn("SLIDE_DURATIONS.reduce", source)
        self.assertIn(": 5;", source)
        self.assertIn("slides.map(normaliseSlidePlanning)", source)
        self.assertIn('assignee: SLIDE_ASSIGNEES[0]', source)
        self.assertIn('durationSeconds: 300', source)
        self.assertIn('>Owner</span><span>Time</span><span>Slide</span>', source)
        self.assertIn("deck-save-status", source)
        self.assertIn('event.altKey', source)
        self.assertIn('event.key !== "ArrowUp"', source)
        self.assertIn(".slide-list-columns", style)
        self.assertNotIn("renderSlideListLegacy", source)
        self.assertNotIn("quick-nav-arrow", source)

    def test_capture_slide_body_copy_reaches_podium_and_phone(self):
        podium = (ROOT / "static" / "podium.js").read_text()
        phone = (ROOT / "static" / "app.js").read_text()
        style = (ROOT / "static" / "style.css").read_text()

        self.assertGreaterEqual(podium.count('class="curation-prompt"'), 3)
        self.assertIn('slide?.body || "What should the bot collect, avoid, or explain?"', phone)
        self.assertIn('slide?.body || "Suggest a stage, or upvote one that looks useful."', phone)
        self.assertIn(".curation-prompt", style)

    def test_slide_images_are_stored_separately_from_slide_json(self):
        main_source = (ROOT / "app" / "main.py").read_text()
        db_source = (ROOT / "app" / "db.py").read_text()

        self.assertIn("presentation_slide_images", db_source)
        self.assertIn("content BYTEA NOT NULL", db_source)
        self.assertIn('@app.put("/api/podium/slides/{slide_id}/image")', main_source)
        self.assertIn('@app.get("/api/podium/slides/{slide_id}/image")', main_source)
        self.assertIn('@app.delete("/api/podium/slides/{slide_id}/image")', main_source)
        self.assertIn("valid_slide_image_signature", main_source)
        self.assertIn("MAX_SLIDE_IMAGE_BYTES", main_source)

    def test_podium_join_box_uses_app_generated_qr_code(self):
        main_source = (ROOT / "app" / "main.py").read_text()
        podium_source = (ROOT / "static" / "podium.js").read_text()
        requirements = (ROOT / "requirements.txt").read_text()

        self.assertIn('/api/qr', main_source)
        self.assertIn('image/svg+xml', main_source)
        self.assertIn('qrcode', requirements)
        self.assertIn('qrImageUrl', podium_source)
        self.assertIn('class="qr-code"', podium_source)
        self.assertIn('/api/qr?text=', podium_source)
        self.assertNotIn('<strong>${esc(qrUrl())}</strong>', podium_source)


if __name__ == "__main__":
    unittest.main()
